version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: cafe_db_container
    environment:
      POSTGRES_DB: cafe_db
      POSTGRES_USER: cafe_user
      POSTGRES_PASSWORD: secure_password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile  
    container_name: cafe_bot_container
    environment:
      - DATABASE_URL=postgresql://cafe_user:secure_password@db:5432/cafe_db
    depends_on:
      - db
    volumes:
      - ./bot:/app
    restart: always

volumes:
  db_data:
